name: test

on:
  push:
    branches:
    - 'main'
    - 'feature-test'
  pull_request:
    branches:
    - 'main'
    - 'feature-test'
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

env:
  TEST_IMAGE_NAME: 'dockerized-shibboleth-idp3:${{ github.sha }}'
  CACHE_IMAGE_NAME: 'dockerized-shibboleth-idp3:cache'
  PUSH_IMAGE_NAME: 'dockerized-shibboleth-idp3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: checkout

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          cd checkout
          docker build ./${PUSH_IMAGE_NAME} -f ./${PUSH_IMAGE_NAME}/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/${TEST_IMAGE_NAME} --tag ${{ secrets.DOCKERHUB_USERNAME }}/${CACHE_IMAGE_NAME}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${CACHE_IMAGE_NAME}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${TEST_IMAGE_NAME}

  hadolint:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
        with:
          path: checkout
      - name: Hadolint the Dockerfile
        run: docker run --rm -i -v $PWD/checkout/.hadolint.yaml:/root/.config/hadolint.yaml hadolint/hadolint < checkout/Dockerfile
