name: Docker Build CI for dockerized-shibboleth-idp3

on:
  push:
    branches: [main, feature-test]
  pull_request:
    branches: [main, feature-test]
  scedule:
    - cron '0 12 * * *'
  workflow_dispatch:

env:
  DOCKER_USERNAME: 'j041128'
  IMAGE_NAME: 'dockerized-shibboleth-idp3'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE-NAME: dockerized-shibboleth-idp3
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: checkout

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${DOCKER_USERNAME}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build the Docker image
        run: |
          cd checkout
          docker build ./${IMAGE_NAME} -f ./${IMAGE_NAME}/Dockerfile --tag ${DOCKER_USERNAME}/${IMAGE_NAME}
          docker push ${DOCKER_USERNAME}/${IMAGE_NAME}
